name: Kayden
version: '1.0-SNAPSHOT'
main: org.jpycode.kayden.Kayden
api-version: '1.21'
commands:
  swords:
    description: A simple menu that contains custom swords.

  status:
    description: Displays the current status of the player.

  money:
    description: Shows user's wallet.

  balance:
    usage: /balance
    aliases:
      - bal
    description: Shows user's wallet.

  pay:

  eco:


