name: Kayden
version: '1.0-SNAPSHOT'
main: com.jpycode.kayden.Kayden
api-version: '1.21'
commands:
  swords:
    description: A simple menu that contains custom swords.

  stats:
    description: Displays the current status of the player.

  money:
    usage: /money
    aliases: [ bal, balance ]
    description: Shows user's wallet.

  pay:
    usage: /pay

  eco:
    usage: /eco

  market:
    usage: /market
